// User Role Colors (Option 1: Primary Colors)
export const ROLE_COLORS = {
  athlete: {
    primary: '#3b82f6', // Blue
    bg: 'bg-blue-500',
    bgLight: 'bg-blue-500/10',
    border: 'border-blue-500',
    text: 'text-blue-500',
    hover: 'hover:bg-blue-600',
  },
  coach: {
    primary: '#22c55e', // Green
    bg: 'bg-green-500',
    bgLight: 'bg-green-500/10',
    border: 'border-green-500',
    text: 'text-green-500',
    hover: 'hover:bg-green-600',
  },
  club: {
    primary: '#f97316', // Orange
    bg: 'bg-orange-500',
    bgLight: 'bg-orange-500/10',
    border: 'border-orange-500',
    text: 'text-orange-500',
    hover: 'hover:bg-orange-600',
  },
} as const

// Football Positions (for athletes)
export const FOOTBALL_POSITIONS = [
  { value: 'QB', label: 'Quarterback' },
  { value: 'RB', label: 'Running Back' },
  { value: 'WR', label: 'Wide Receiver' },
  { value: 'TE', label: 'Tight End' },
  { value: 'OL', label: 'Offensive Line' },
  { value: 'DL', label: 'Defensive Line' },
  { value: 'LB', label: 'Linebacker' },
  { value: 'CB', label: 'Cornerback' },
  { value: 'S', label: 'Safety' },
  { value: 'K', label: 'Kicker' },
  { value: 'P', label: 'Punter' },
  { value: 'ATH', label: 'Athlete' },
] as const

// Graduation Years
export const GRADUATION_YEARS = [
  { value: 2025, label: '2025' },
  { value: 2026, label: '2026' },
  { value: 2027, label: '2027' },
  { value: 2028, label: '2028' },
  { value: 2029, label: '2029' },
  { value: 2030, label: '2030' },
] as const

export const DIVISIONS = [
  { value: 'FBS', label: 'FBS (Division I)' },
  { value: 'FCS', label: 'FCS (Division I-AA)' },
  { value: 'D2', label: 'Division II' },
  { value: 'D3', label: 'Division III' },
  { value: 'NAIA', label: 'NAIA' },
  { value: 'JUCO', label: 'Junior College' },
] as const

export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DC', label: 'District of Columbia' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
] as const

export const CONFERENCES = [
  { value: 'SEC', label: 'SEC' },
  { value: 'Big Ten', label: 'Big Ten' },
  { value: 'ACC', label: 'ACC' },
  { value: 'Big 12', label: 'Big 12' },
  { value: 'Pac-12', label: 'Pac-12' },
  { value: 'American', label: 'American Athletic' },
  { value: 'Mountain West', label: 'Mountain West' },
  { value: 'Sun Belt', label: 'Sun Belt' },
  { value: 'MAC', label: 'MAC' },
  { value: 'Conference USA', label: 'Conference USA' },
  { value: 'Big Sky', label: 'Big Sky' },
  { value: 'SWAC', label: 'SWAC' },
  { value: 'MEAC', label: 'MEAC' },
  { value: 'Ivy League', label: 'Ivy League' },
  { value: 'Patriot League', label: 'Patriot League' },
  { value: 'Pioneer', label: 'Pioneer' },
  { value: 'Southern', label: 'Southern' },
  { value: 'Ohio Valley', label: 'Ohio Valley' },
  { value: 'Missouri Valley', label: 'Missouri Valley' },
  { value: 'CAA', label: 'CAA' },
  { value: 'Northeast', label: 'Northeast' },
] as const
